version: '3'
services:
  treeo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3000 # to test, use port 3003
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    # environment:
    #   POSTGRES_DB: treeoDB
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
